# SPDX-FileCopyrightText: Copyright 2020-present Open Networking Foundation.
# SPDX-License-Identifier: Apache-2.0

name: Container Image
on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
  pull_request:
    branches:
      - master
    paths:
      - Dockerfile
jobs:
  build_container_image:
    name: Build the container image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        run: docker buildx build .
