# SPDX-FileCopyrightText: Copyright 2020-present Open Networking Foundation.
# SPDX-License-Identifier: Apache-2.0

name: REUSE
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_reuse_tool:
    name: Run REUSE tool to check license
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1
